In [1]:
import numpy as np

In [3]:
list_ = ['1','2','3','4','5']

In [4]:
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [5]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [8]:
array_list.dtype

dtype('<U1')

In [9]:
variables_list= np.array(object = list_)

In [10]:
variables_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [11]:
variables_list.dtype

dtype('<U1')

there is no differene between variables list_ and array_list

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [12]:
list_var = [1, 2, 3, 4, 5]

In [13]:
array_var = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

In [14]:
for element in list_var:
    print(f"Data type of {element}: {type(element)}")

Data type of 1: <class 'int'>
Data type of 2: <class 'int'>
Data type of 3: <class 'int'>
Data type of 4: <class 'int'>
Data type of 5: <class 'int'>


In [16]:
for element in array_var:
    print(f"Data type of {element}: {type(element)}")

Data type of 1.1: <class 'numpy.float64'>
Data type of 2.2: <class 'numpy.float64'>
Data type of 3.3: <class 'numpy.float64'>
Data type of 4.4: <class 'numpy.float64'>
Data type of 5.5: <class 'numpy.float64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [18]:
a=[1,2,3,4,5,6]

In [19]:
num_array=np.array(a)

In [20]:
num_array

array([1, 2, 3, 4, 5, 6])

In [21]:
num_array.shape

(6,)

In [22]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])